name: Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - 
      name: Check out Repo
      uses: actions/checkout@v4
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Registry (Github Packages)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: x4132.dev:latest
